class CreateCountries < ActiveRecord::Migration[7.0]
  class MigrationCountry < ActiveRecord::Base
    self.table_name = 'countries'
  end

  def up
    create_table :countries do |t|
      t.string :code, null: false
      t.string :title
      t.string :title_ru
      t.string :flag
      t.integer :position, default: 0, null: false

      t.timestamps
    end
    add_index :countries, :code, unique: true
    add_index :countries, :position

    MigrationCountry.reset_column_information

    countries_data.each_with_index do |attrs, idx|
      MigrationCountry.create!(attrs.merge(position: idx))
    end
  end

  def down
    drop_table :countries
  end

  def countries_data
    [
      { code: 'AFG', title: 'Afghanistan', title_ru: 'Афганистан', flag: '🇦🇫' },
      { code: 'ALB', title: 'Albania', title_ru: 'Албания', flag: '🇦🇱' },
      { code: 'DZA', title: 'Algeria', title_ru: 'Алжир', flag: '🇩🇿' },
      { code: 'ASM', title: 'American Samoa', title_ru: 'Американское Самоа', flag: '🇦🇸' },
      { code: 'AND', title: 'Andorra', title_ru: 'Андорра', flag: '🇦🇩' },
      { code: 'AGO', title: 'Angola', title_ru: 'Ангола', flag: '🇦🇴' },
      { code: 'AIA', title: 'Anguilla', title_ru: 'Ангилья', flag: '🇦🇮' },
      { code: 'ATA', title: 'Antarctica', title_ru: 'Антарктида', flag: '🏳️' },
      { code: 'ATG', title: 'Antigua and Barbuda', title_ru: 'Антигуа и Барбуда', flag: '🇦🇬' },
      { code: 'ARG', title: 'Argentina', title_ru: 'Аргентина', flag: '🇦🇷' },
      { code: 'ARM', title: 'Armenia', title_ru: 'Армения', flag: '🇦🇲' },
      { code: 'ABW', title: 'Aruba', title_ru: 'Аруба', flag: '🇦🇼' },
      { code: 'AUS', title: 'Australia', title_ru: 'Австралия', flag: '🇦🇺' },
      { code: 'AUT', title: 'Austria', title_ru: 'Австрия', flag: '🇦🇹' },
      { code: 'AZE', title: 'Azerbaijan', title_ru: 'Азербайджан', flag: '🇦🇿' },
      { code: 'BHS', title: 'Bahamas', title_ru: 'Багамы', flag: '🇧🇸' },
      { code: 'BHR', title: 'Bahrain', title_ru: 'Бахрейн', flag: '🇧🇭' },
      { code: 'BGD', title: 'Bangladesh', title_ru: 'Бангладеш', flag: '🇧🇩' },
      { code: 'BRB', title: 'Barbados', title_ru: 'Барбадос', flag: '🇧🇧' },
      { code: 'BLR', title: 'Belarus', title_ru: 'Беларусь', flag: '🇧🇾' },
      { code: 'BEL', title: 'Belgium', title_ru: 'Бельгия', flag: '🇧🇪' },
      { code: 'BLZ', title: 'Belize', title_ru: 'Белиз', flag: '🇧🇿' },
      { code: 'BEN', title: 'Benin', title_ru: 'Бенин', flag: '🇧🇯' },
      { code: 'BMU', title: 'Bermuda', title_ru: 'Бермуды', flag: '🇧🇲' },
      { code: 'BTN', title: 'Bhutan', title_ru: 'Бутан', flag: '🇧🇹' },
      { code: 'BOL', title: 'Bolivia, Plurinational State of', title_ru: 'Боливия', flag: '🇧🇴' },
      { code: 'BIH', title: 'Bosnia and Herzegovina', title_ru: 'Босния и Герцеговина', flag: '🇧🇦' },
      { code: 'BWA', title: 'Botswana', title_ru: 'Ботсвана', flag: '🇧🇼' },
      { code: 'BVT', title: 'Bouvet Island', title_ru: 'Остров Буве', flag: '🏳️' },
      { code: 'BRA', title: 'Brazil', title_ru: 'Бразилия', flag: '🇧🇷' },
      { code: 'IOT', title: 'British Indian Ocean Territory', title_ru: 'Британская территория в Индийском океане', flag: '🏳️' },
      { code: 'BRN', title: 'Brunei Darussalam', title_ru: 'Бруней', flag: '🇧🇳' },
      { code: 'BGR', title: 'Bulgaria', title_ru: 'Болгария', flag: '🇧🇬' },
      { code: 'BFA', title: 'Burkina Faso', title_ru: 'Буркина-Фасо', flag: '🇧🇫' },
      { code: 'BDI', title: 'Burundi', title_ru: 'Бурунди', flag: '🇧🇮' },
      { code: 'KHM', title: 'Cambodia', title_ru: 'Камбоджа', flag: '🇰🇭' },
      { code: 'CMR', title: 'Cameroon', title_ru: 'Камерун', flag: '🇨🇲' },
      { code: 'CAN', title: 'Canada', title_ru: 'Канада', flag: '🇨🇦' },
      { code: 'CPV', title: 'Cape Verde', title_ru: 'Кабо-Верде', flag: '🇨🇻' },
      { code: 'CYM', title: 'Cayman Islands', title_ru: 'Каймановы острова', flag: '🇰🇾' },
      { code: 'CAF', title: 'Central African Republic', title_ru: 'Центральноафриканская Республика', flag: '🇨🇫' },
      { code: 'TCD', title: 'Chad', title_ru: 'Чад', flag: '🇹🇩' },
      { code: 'CHL', title: 'Chile', title_ru: 'Чили', flag: '🇨🇱' },
      { code: 'CHN', title: 'China', title_ru: 'Китай', flag: '🇨🇳' },
      { code: 'CXR', title: 'Christmas Island', title_ru: 'Остров Рождества', flag: '🇨🇽' },
      { code: 'CCK', title: 'Cocos (Keeling) Islands', title_ru: 'Кокосовые (Килинг) острова', flag: '🇨🇨' },
      { code: 'COL', title: 'Colombia', title_ru: 'Колумбия', flag: '🇨🇴' },
      { code: 'COM', title: 'Comoros', title_ru: 'Коморы', flag: '🇰🇲' },
      { code: 'COG', title: 'Congo', title_ru: 'Конго', flag: '🇨🇬' },
      { code: 'COK', title: 'Cook Islands', title_ru: 'Острова Кука', flag: '🇨🇰' },
      { code: 'CRI', title: 'Costa Rica', title_ru: 'Коста-Рика', flag: '🇨🇷' },
      { code: 'CIV', title: "Cote d'Ivoire ! Côte d'Ivoire", title_ru: 'Кот-д’Ивуар', flag: '🇨🇮' },
      { code: 'HRV', title: 'Croatia', title_ru: 'Хорватия', flag: '🇭🇷' },
      { code: 'CUB', title: 'Cuba', title_ru: 'Куба', flag: '🇨🇺' },
      { code: 'CYP', title: 'Cyprus', title_ru: 'Кипр', flag: '🇨🇾' },
      { code: 'CZE', title: 'Czech Republic', title_ru: 'Чехия', flag: '🇨🇿' },
      { code: 'ZAR', title: 'Democratic Republic of Congo (Zaire)', title_ru: 'Демократическая Республика Конго (Заир)', flag: '🇨🇩' },
      { code: 'DNK', title: 'Denmark', title_ru: 'Дания', flag: '🇩🇰' },
      { code: 'DJI', title: 'Djibouti', title_ru: 'Джибути', flag: '🇩🇯' },
      { code: 'DMA', title: 'Dominica', title_ru: 'Доминика', flag: '🇩🇲' },
      { code: 'DOM', title: 'Dominican Republic', title_ru: 'Доминиканская Республика', flag: '🇩🇴' },
      { code: 'TMP', title: 'East Timor', title_ru: 'Восточный Тимор', flag: '🇹🇱' },
      { code: 'ECU', title: 'Ecuador', title_ru: 'Эквадор', flag: '🇪🇨' },
      { code: 'EGY', title: 'Egypt', title_ru: 'Египет', flag: '🇪🇬' },
      { code: 'SLV', title: 'El Salvador', title_ru: 'Сальвадор', flag: '🇸🇻' },
      { code: 'GNQ', title: 'Equatorial Guinea', title_ru: 'Экваториальная Гвинея', flag: '🇬🇶' },
      { code: 'ERI', title: 'Eritrea', title_ru: 'Эритрея', flag: '🇪🇷' },
      { code: 'EST', title: 'Estonia', title_ru: 'Эстония', flag: '🇪🇪' },
      { code: 'ETH', title: 'Ethiopia', title_ru: 'Эфиопия', flag: '🇪🇹' },
      { code: 'FLK', title: 'Falkland Islands (Malvinas)', title_ru: 'Фолклендские (Мальвинские) острова', flag: '🇫🇰' },
      { code: 'FRO', title: 'Faroe Islands', title_ru: 'Фарерские острова', flag: '🇫🇴' },
      { code: 'FJI', title: 'Fiji', title_ru: 'Фиджи', flag: '🇫🇯' },
      { code: 'FIN', title: 'Finland', title_ru: 'Финляндия', flag: '🇫🇮' },
      { code: 'FRA', title: 'France', title_ru: 'Франция', flag: '🇫🇷' },
      { code: 'FXX', title: 'France, Metropolis', title_ru: 'Франция (метрополия)', flag: '🇫🇷' },
      { code: 'GUF', title: 'French Guiana', title_ru: 'Французская Гвиана', flag: '🇬🇫' },
      { code: 'PYF', title: 'French Polynesia', title_ru: 'Французская Полинезия', flag: '🇵🇫' },
      { code: 'ATF', title: 'French Southern Territories', title_ru: 'Французские Южные территории', flag: '🏳️' },
      { code: 'GAB', title: 'Gabon', title_ru: 'Габон', flag: '🇬🇦' },
      { code: 'GMB', title: 'Gambia', title_ru: 'Гамбия', flag: '🇬🇲' },
      { code: 'GEO', title: 'Georgia', title_ru: 'Грузия', flag: '🇬🇪' },
      { code: 'DEU', title: 'Germany', title_ru: 'Германия', flag: '🇩🇪' },
      { code: 'GHA', title: 'Ghana', title_ru: 'Гана', flag: '🇬🇭' },
      { code: 'GIB', title: 'Gibraltar', title_ru: 'Гибралтар', flag: '🇬🇮' },
      { code: 'GRC', title: 'Greece', title_ru: 'Греция', flag: '🇬🇷' },
      { code: 'GRL', title: 'Greenland', title_ru: 'Гренландия', flag: '🇬🇱' },
      { code: 'GRD', title: 'Grenada', title_ru: 'Гренада', flag: '🇬🇩' },
      { code: 'GLP', title: 'Guadeloupe', title_ru: 'Гваделупа', flag: '🇬🇵' },
      { code: 'GUM', title: 'Guam', title_ru: 'Гуам', flag: '🇬🇺' },
      { code: 'GTM', title: 'Guatemala', title_ru: 'Гватемала', flag: '🇬🇹' },
      { code: 'GIN', title: 'Guinea', title_ru: 'Гвинея', flag: '🇬🇳' },
      { code: 'GNB', title: 'Guinea-Bissau', title_ru: 'Гвинея-Бисау', flag: '🇬🇼' },
      { code: 'GUY', title: 'Guyana', title_ru: 'Гайана', flag: '🇬🇾' },
      { code: 'HTI', title: 'Haiti', title_ru: 'Гаити', flag: '🇭🇹' },
      { code: 'HMD', title: 'Heard Island and McDonald Islands', title_ru: 'Остров Херд и острова Макдональд', flag: '🏳️' },
      { code: 'VAT', title: 'Holy See (Vatican City State)', title_ru: 'Ватикан', flag: '🇻🇦' },
      { code: 'HND', title: 'Honduras', title_ru: 'Гондурас', flag: '🇭🇳' },
      { code: 'HKG', title: 'Hong Kong', title_ru: 'Гонконг', flag: '🇭🇰' },
      { code: 'HUN', title: 'Hungary', title_ru: 'Венгрия', flag: '🇭🇺' },
      { code: 'ISL', title: 'Iceland', title_ru: 'Исландия', flag: '🇮🇸' },
      { code: 'IND', title: 'India', title_ru: 'Индия', flag: '🇮🇳' },
      { code: 'IDN', title: 'Indonesia', title_ru: 'Индонезия', flag: '🇮🇩' },
      { code: 'IRN', title: 'Iran, Islamic Republic of', title_ru: 'Иран', flag: '🇮🇷' },
      { code: 'IRQ', title: 'Iraq', title_ru: 'Ирак', flag: '🇮🇶' },
      { code: 'IRL', title: 'Ireland', title_ru: 'Ирландия', flag: '🇮🇪' },
      { code: 'ISR', title: 'Israel', title_ru: 'Израиль', flag: '🇮🇱' },
      { code: 'ITA', title: 'Italy', title_ru: 'Италия', flag: '🇮🇹' },
      { code: 'JAM', title: 'Jamaica', title_ru: 'Ямайка', flag: '🇯🇲' },
      { code: 'JPN', title: 'Japan', title_ru: 'Япония', flag: '🇯🇵' },
      { code: 'JOR', title: 'Jordan', title_ru: 'Иордания', flag: '🇯🇴' },
      { code: 'KAZ', title: 'Kazakhstan', title_ru: 'Казахстан', flag: '🇰🇿' },
      { code: 'KEN', title: 'Kenya', title_ru: 'Кения', flag: '🇰🇪' },
      { code: 'KIR', title: 'Kiribati', title_ru: 'Кирибати', flag: '🇰🇮' },
      { code: 'KWT', title: 'Kuwait', title_ru: 'Кувейт', flag: '🇰🇼' },
      { code: 'KGZ', title: 'Kyrgyzstan', title_ru: 'Киргизия', flag: '🇰🇬' },
      { code: 'LAO', title: "Lao People's Democratic Republic", title_ru: 'Лаос', flag: '🇱🇦' },
      { code: 'LVA', title: 'Latvia', title_ru: 'Латвия', flag: '🇱🇻' },
      { code: 'LBN', title: 'Lebanon', title_ru: 'Ливан', flag: '🇱🇧' },
      { code: 'LSO', title: 'Lesotho', title_ru: 'Лесото', flag: '🇱🇸' },
      { code: 'LBR', title: 'Liberia', title_ru: 'Либерия', flag: '🇱🇷' },
      { code: 'LBY', title: 'Libyan Arab Jamahiriya', title_ru: 'Ливия', flag: '🇱🇾' },
      { code: 'LIE', title: 'Liechtenstein', title_ru: 'Лихтенштейн', flag: '🇱🇮' },
      { code: 'LTU', title: 'Lithuania', title_ru: 'Литва', flag: '🇱🇹' },
      { code: 'LUX', title: 'Luxembourg', title_ru: 'Люксембург', flag: '🇱🇺' },
      { code: 'MAC', title: 'Macao', title_ru: 'Макао', flag: '🇲🇴' },
      { code: 'MKD', title: 'Macedonia, the former Yugoslav Republic of', title_ru: 'Северная Македония', flag: '🇲🇰' },
      { code: 'MDG', title: 'Madagascar', title_ru: 'Мадагаскар', flag: '🇲🇬' },
      { code: 'MWI', title: 'Malawi', title_ru: 'Малави', flag: '🇲🇼' },
      { code: 'MYS', title: 'Malaysia', title_ru: 'Малайзия', flag: '🇲🇾' },
      { code: 'MDV', title: 'Maldives', title_ru: 'Мальдивы', flag: '🇲🇻' },
      { code: 'MLI', title: 'Mali', title_ru: 'Мали', flag: '🇲🇱' },
      { code: 'MLT', title: 'Malta', title_ru: 'Мальта', flag: '🇲🇹' },
      { code: 'MHL', title: 'Marshall Islands', title_ru: 'Маршалловы острова', flag: '🇲🇭' },
      { code: 'MTQ', title: 'Martinique', title_ru: 'Мартиника', flag: '🇲🇶' },
      { code: 'MRT', title: 'Mauritania', title_ru: 'Мавритания', flag: '🇲🇷' },
      { code: 'MUS', title: 'Mauritius', title_ru: 'Маврикий', flag: '🇲🇺' },
      { code: 'MYT', title: 'Mayotte', title_ru: 'Майотта', flag: '🇾🇹' },
      { code: 'MEX', title: 'Mexico', title_ru: 'Мексика', flag: '🇲🇽' },
      { code: 'FSM', title: 'Micronesia, Federated States of', title_ru: 'Микронезия', flag: '🇫🇲' },
      { code: 'MDA', title: 'Moldova, Republic of', title_ru: 'Молдова', flag: '🇲🇩' },
      { code: 'MCO', title: 'Monaco', title_ru: 'Монако', flag: '🇲🇨' },
      { code: 'MNG', title: 'Mongolia', title_ru: 'Монголия', flag: '🇲🇳' },
      { code: 'MNE', title: 'Montenegro', title_ru: 'Черногория', flag: '🇲🇪' },
      { code: 'MSR', title: 'Montserrat', title_ru: 'Монтсеррат', flag: '🇲🇸' },
      { code: 'MAR', title: 'Morocco', title_ru: 'Марокко', flag: '🇲🇦' },
      { code: 'MOZ', title: 'Mozambique', title_ru: 'Мозамбик', flag: '🇲🇿' },
      { code: 'MMR', title: 'Myanmar', title_ru: 'Мьянма', flag: '🇲🇲' },
      { code: 'NAM', title: 'Namibia', title_ru: 'Намибия', flag: '🇳🇦' },
      { code: 'NRU', title: 'Nauru', title_ru: 'Науру', flag: '🇳🇷' },
      { code: 'NPL', title: 'Nepal', title_ru: 'Непал', flag: '🇳🇵' },
      { code: 'NLD', title: 'Netherlands', title_ru: 'Нидерланды', flag: '🇳🇱' },
      { code: 'ANT', title: 'Netherlands Antilles', title_ru: 'Нидерландские Антильские острова', flag: '🏳️' },
      { code: 'NCL', title: 'New Caledonia', title_ru: 'Новая Каледония', flag: '🇳🇨' },
      { code: 'NZL', title: 'New Zealand', title_ru: 'Новая Зеландия', flag: '🇳🇿' },
      { code: 'NIC', title: 'Nicaragua', title_ru: 'Никарагуа', flag: '🇳🇮' },
      { code: 'NER', title: 'Niger', title_ru: 'Нигер', flag: '🇳🇪' },
      { code: 'NGA', title: 'Nigeria', title_ru: 'Нигерия', flag: '🇳🇬' },
      { code: 'NIU', title: 'Niue', title_ru: 'Ниуэ', flag: '🇳🇺' },
      { code: 'NFK', title: 'Norfolk Island', title_ru: 'Остров Норфолк', flag: '🇳🇫' },
      { code: 'PRK', title: 'North Korea', title_ru: 'Северная Корея', flag: '🇰🇵' },
      { code: 'MNP', title: 'Northern Mariana Islands', title_ru: 'Северные Марианские острова', flag: '🇲🇵' },
      { code: 'NOR', title: 'Norway', title_ru: 'Норвегия', flag: '🇳🇴' },
      { code: 'OMN', title: 'Oman', title_ru: 'Оман', flag: '🇴🇲' },
      { code: 'PAK', title: 'Pakistan', title_ru: 'Пакистан', flag: '🇵🇰' },
      { code: 'PLE', title: 'Palestine', title_ru: 'Палестина', flag: '🇵🇸' },
      { code: 'PLW', title: 'Palau', title_ru: 'Палау', flag: '🇵🇼' },
      { code: 'PAN', title: 'Panama', title_ru: 'Панама', flag: '🇵🇦' },
      { code: 'PNG', title: 'Papua New Guinea', title_ru: 'Папуа — Новая Гвинея', flag: '🇵🇬' },
      { code: 'PRY', title: 'Paraguay', title_ru: 'Парагвай', flag: '🇵🇾' },
      { code: 'PER', title: 'Peru', title_ru: 'Перу', flag: '🇵🇪' },
      { code: 'PHL', title: 'Philippines', title_ru: 'Филиппины', flag: '🇵🇭' },
      { code: 'PCN', title: 'Pitcairn', title_ru: 'Острова Питкэрн', flag: '🇵🇳' },
      { code: 'POL', title: 'Poland', title_ru: 'Польша', flag: '🇵🇱' },
      { code: 'PRT', title: 'Portugal', title_ru: 'Португалия', flag: '🇵🇹' },
      { code: 'PRI', title: 'Puerto Rico', title_ru: 'Пуэрто-Рико', flag: '🇵🇷' },
      { code: 'QAT', title: 'Qatar', title_ru: 'Катар', flag: '🇶🇦' },
      { code: 'REU', title: 'Reunion ! Réunion', title_ru: 'Реюньон', flag: '🇷🇪' },
      { code: 'ROU', title: 'Romania', title_ru: 'Румыния', flag: '🇷🇴' },
      { code: 'RUS', title: 'Russian Federation', title_ru: 'Россия', flag: '🇷🇺' },
      { code: 'RWA', title: 'Rwanda', title_ru: 'Руанда', flag: '🇷🇼' },
      { code: 'SHN', title: 'Saint Helena, Ascension and Tristan da Cunha', title_ru: 'Святая Елена, Вознесение и Тристан-да-Кунья', flag: '🇸🇭' },
      { code: 'KNA', title: 'Saint Kitts and Nevis', title_ru: 'Сент-Китс и Невис', flag: '🇰🇳' },
      { code: 'LCA', title: 'Saint Lucia', title_ru: 'Сент-Люсия', flag: '🇱🇨' },
      { code: 'SPM', title: 'Saint Pierre and Miquelon', title_ru: 'Сен-Пьер и Микелон', flag: '🇵🇲' },
      { code: 'VCT', title: 'Saint Vincent and the Grenadines', title_ru: 'Сент-Винсент и Гренадины', flag: '🇻🇨' },
      { code: 'WSM', title: 'Samoa', title_ru: 'Самоа', flag: '🇼🇸' },
      { code: 'SMR', title: 'San Marino', title_ru: 'Сан-Марино', flag: '🇸🇲' },
      { code: 'STP', title: 'Sao Tome and Principe', title_ru: 'Сан-Томе и Принсипи', flag: '🇸🇹' },
      { code: 'SAU', title: 'Saudi Arabia', title_ru: 'Саудовская Аравия', flag: '🇸🇦' },
      { code: 'SEN', title: 'Senegal', title_ru: 'Сенегал', flag: '🇸🇳' },
      { code: 'SRB', title: 'Serbia', title_ru: 'Сербия', flag: '🇷🇸' },
      { code: 'SYC', title: 'Seychelles', title_ru: 'Сейшелы', flag: '🇸🇨' },
      { code: 'SLE', title: 'Sierra Leone', title_ru: 'Сьерра-Леоне', flag: '🇸🇱' },
      { code: 'SGP', title: 'Singapore', title_ru: 'Сингапур', flag: '🇸🇬' },
      { code: 'SVK', title: 'Slovakia', title_ru: 'Словакия', flag: '🇸🇰' },
      { code: 'SVN', title: 'Slovenia', title_ru: 'Словения', flag: '🇸🇮' },
      { code: 'SLB', title: 'Solomon Islands', title_ru: 'Соломоновы острова', flag: '🇸🇧' },
      { code: 'SOM', title: 'Somalia', title_ru: 'Сомали', flag: '🇸🇴' },
      { code: 'ZAF', title: 'South Africa', title_ru: 'ЮАР', flag: '🇿🇦' },
      { code: 'SGS', title: 'South Georgia and the South Sandwich Islands', title_ru: 'Южная Георгия и Южные Сандвичевы острова', flag: '🇬🇸' },
      { code: 'KOR', title: 'South Korea', title_ru: 'Южная Корея', flag: '🇰🇷' },
      { code: 'OST', title: 'South Ossetia', title_ru: 'Южная Осетия', flag: '🏳️' },
      { code: 'ESP', title: 'Spain', title_ru: 'Испания', flag: '🇪🇸' },
      { code: 'LKA', title: 'Sri Lanka', title_ru: 'Шри-Ланка', flag: '🇱🇰' },
      { code: 'SDN', title: 'Sudan', title_ru: 'Судан', flag: '🇸🇩' },
      { code: 'SUR', title: 'Suriname', title_ru: 'Суринам', flag: '🇸🇷' },
      { code: 'SJM', title: 'Svalbard and Jan Mayen', title_ru: 'Шпицберген и Ян-Майен', flag: '🇸🇯' },
      { code: 'SWZ', title: 'Swaziland', title_ru: 'Эсватини', flag: '🇸🇿' },
      { code: 'SWE', title: 'Sweden', title_ru: 'Швеция', flag: '🇸🇪' },
      { code: 'CHE', title: 'Switzerland', title_ru: 'Швейцария', flag: '🇨🇭' },
      { code: 'SYR', title: 'Syrian Arab Republic', title_ru: 'Сирия', flag: '🇸🇾' },
      { code: 'TWN', title: 'Taiwan, Republic of China', title_ru: 'Тайвань', flag: '🇹🇼' },
      { code: 'TJK', title: 'Tajikistan', title_ru: 'Таджикистан', flag: '🇹🇯' },
      { code: 'TZA', title: 'Tanzania, United Republic of', title_ru: 'Танзания', flag: '🇹🇿' },
      { code: 'THA', title: 'Thailand', title_ru: 'Таиланд', flag: '🇹🇭' },
      { code: 'TGO', title: 'Togo', title_ru: 'Того', flag: '🇹🇬' },
      { code: 'TKL', title: 'Tokelau', title_ru: 'Токелау', flag: '🇹🇰' },
      { code: 'TON', title: 'Tonga', title_ru: 'Тонга', flag: '🇹🇴' },
      { code: 'TTO', title: 'Trinidad and Tobago', title_ru: 'Тринидад и Тобаго', flag: '🇹🇹' },
      { code: 'TUN', title: 'Tunisia', title_ru: 'Тунис', flag: '🇹🇳' },
      { code: 'TUR', title: 'Turkey', title_ru: 'Турция', flag: '🇹🇷' },
      { code: 'TKM', title: 'Turkmenistan', title_ru: 'Туркменистан', flag: '🇹🇲' },
      { code: 'TCA', title: 'Turks and Caicos Islands', title_ru: 'Теркс и Кайкос', flag: '🇹🇨' },
      { code: 'TUV', title: 'Tuvalu', title_ru: 'Тувалу', flag: '🇹🇻' },
      { code: 'UGA', title: 'Uganda', title_ru: 'Уганда', flag: '🇺🇬' },
      { code: 'UKR', title: 'Ukraine', title_ru: 'Украина', flag: '🇺🇦' },
      { code: 'ARE', title: 'United Arab Emirates', title_ru: 'ОАЭ', flag: '🇦🇪' },
      { code: 'GBR', title: 'United Kingdom', title_ru: 'Великобритания', flag: '🇬🇧' },
      { code: 'USA', title: 'United States', title_ru: 'США', flag: '🇺🇸' },
      { code: 'UMI', title: 'United States Minor Outlying Islands', title_ru: 'Внешние малые острова США', flag: '🇺🇲' },
      { code: 'URY', title: 'Uruguay', title_ru: 'Уругвай', flag: '🇺🇾' },
      { code: 'UZB', title: 'Uzbekistan', title_ru: 'Узбекистан', flag: '🇺🇿' },
      { code: 'VUT', title: 'Vanuatu', title_ru: 'Вануату', flag: '🇻🇺' },
      { code: 'VEN', title: 'Venezuela, Bolivarian Republic of', title_ru: 'Венесуэла', flag: '🇻🇪' },
      { code: 'VNM', title: 'Viet Nam', title_ru: 'Вьетнам', flag: '🇻🇳' },
      { code: 'VGB', title: 'Virgin Islands, British', title_ru: 'Британские Виргинские острова', flag: '🇻🇬' },
      { code: 'VIR', title: 'Virgin Islands, U.S.', title_ru: 'Виргинские острова США', flag: '🇻🇮' },
      { code: 'WLF', title: 'Wallis and Futuna', title_ru: 'Уоллис и Футуна', flag: '🇼🇫' },
      { code: 'ESH', title: 'Western Sahara', title_ru: 'Западная Сахара', flag: '🇪🇭' },
      { code: 'NON', title: 'Without citizenship', title_ru: 'Без гражданства', flag: '🏳️' },
      { code: 'YEM', title: 'Yemen', title_ru: 'Йемен', flag: '🇾🇪' },
      { code: 'ZMB', title: 'Zambia', title_ru: 'Замбия', flag: '🇿🇲' },
      { code: 'ZWE', title: 'Zimbabwe', title_ru: 'Зимбабве', flag: '🇿🇼' }
    ]
  end
end